### ISSUE TITLE
Пожелания.

### ISSUE THREAD

**Issue by conrad66** [MJeka/air_conditioning#1]
Добрый день !
Отличное дополнение для кондиционера панасоник !!
Но есть пожелания ))
1. Можно ли добавить шаг изменения температуры ( сейчас 0.5 фиксировано )
2. Шторки... Хотелось бы выбор режима шторок.
3. Ну и было бы совсем отлично поиметь управление горизонтальными шторками ( у меня с пульта управляются )
4.  current_temperature: null ( как бы ее задать и где .... )

**Comment by MJeka** [comment]
1. Шаг на пульте у меня тоже 0,5 градусов, да и смысла нет ловить меньше, т.к. температура у пола и у потолка очень сильно отличается, особенно если попадает солнце. Если я правильно помню, то там выделено только 32 бита в протоколе под температуру, а это шаг в 0,5 градуса. 32-16 = 16/0,5 = 32 бита (0-31) Так сделано в самом протоколе обмена

2. Положение заслонки жестко выставляется в файле panasonic_ir.h строчки 14-17. Я выбрал режим, который мне подходит и жестко его задаю. Как менять положение заслонок через Home Assistant не разбирался, т.к. не было необходимости. Положение всегда фиксированное и одно.
3. Там же можно выставить и горизонтальное положение, добавил положения, нужно обновиться.
4. Все это делается через автоматизации в НА и сохранением состояния в MQTT или inputs
```
automation:
  - id: "Балкон A/C: включение кондиционера"
    alias: balconyac_on
   initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.lr_remote_control_action
        to: 1_double
    condition:
      - condition: state
        entity_id: binary_sensor.bn_ac_control_general
        state: "on"
    action:
      - choose:
          - conditions:
              ## Кондиционер выключен
              - condition: state
                entity_id: binary_sensor.balconyac_work_sensor
                state: "off"
            sequence:
              - service: climate.set_temperature
                data:
                  temperature: 25
                  hvac_mode: heat
                target:
                  entity_id: climate.balconyac
              - delay: 2
              - service: climate.set_preset_mode
                target:
                  entity_id: climate.balconyac
                data:
                  preset_mode: none
        default:
          - service: climate.turn_off
            target:
              entity_id: climate.balconyac
    mode: queued
    max: 5
``` 
У меня сделано так, что основные функции я вынес на 4-х кнопочный Zigbee пульт и управляю кондиционером через Home Assistant. Поэтому температура установки и режимы сохраняются средствами HA. Пульт кондиционера практически перестал использоваться.
